### PR TITLE
Update read_data_test.rb to work with secured endpoints

### LINKED ISSUE #22: bearer parameter from the Import Manifest is not used
Hello,

The "Import Manifest" tests do not seem to parse the "bearer" parameter (`parameter:udsData.part:importAccessToken`) when making requests.
https://github.com/inferno-framework/uds-plus-test-kit/blob/4999db590f7cee5d3595051fac8ab44cc3783c75/lib/uds_plus_test_kit/manifest_tests/read_data_test.rb#L40-L47

As a result, URLs that require authentication cannot be tested.

### PR DESCRIPTION
**Pull request by hbader93**
# Summary
Pulls out the Bearer token from the posted UDS+ manifest if it is part of the manifest.
Then uses relevant token in followup request for the given Bulk FHIR file. 
Enables testing against FileRequest endpoints that require an authenticated request.

Resolves #22

### CODE REVIEW

**Comment by rpassas** [comment]
Per the response of @ljtucker on [issue 22](https://github.com/inferno-framework/uds-plus-test-kit/issues/22), authentication is out of scope for this iteration of the test kit.

**Comment by hbader93** [comment]
In that case, I'll add on some of my thoughts to that chain. 

I think this should be in scope for the current version of the test kit, and I'm happy to make any needed changes to the pull request to get this added to the repo.

**Comment by ljtucker** [comment]
Hi @hbader93 and @rpassas, we have discussed this addition internally and see the benefit of its inclusion. We would like to integrate this addition into our upcoming release of the Test Kit, which will coincide with the release of v1.0.2 of the UDS+ IG. @hbader93, thank you for your work building this addition! Have you verified that these changes allow the test to successfully extract ndjson data for Import Manifests with AND without bearer tokens?

**Comment by hbader93** [comment]
@ljtucker Sorry for the delay. I spent a bit of time getting a local unsecured instance up and running / connected, but the current code does work both with AND without bearer tokens.

image

Disclaimer: The data I've been testing with is a bit sparse, so there are a few warnings as to some data being missing, but to me that offers more evidence to it working.

**Review by rpassas — APPROVED** [review]

**Pull request merged**
